name: CI

on:
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]


jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint main-cookbooks
      run: |
        cd provisioners/chef_solo
        docker-compose up --exit-code-from lint lint

  install:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install vendor-cookbooks
      run: |
        cd provisioners/chef_solo
        docker-compose up --exit-code-from install install

    # only on develop branch
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "vendor-cookbooks updated from CI" || true # ok if no changes
      if: github.ref == 'refs/heads/develop'

    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: develop
      if: github.ref == 'refs/heads/develop'
